boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupts.o: interrupts.c x86_desc.h types.h interrupts.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h interrupts.h drivers/rtc.h
lib.o: lib.c lib.h types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h drivers/rtc.h
rtc.o: drivers/rtc.c drivers/../lib.h drivers/../types.h \
  drivers/../i8259.h drivers/rtc.h
